/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package entrepriseapp;

import javax.swing.UIManager;

/**
 *
 * @author zGuindouOS
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form App
     */
    public App() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            e.printStackTrace();
        }
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
    }
    
    static public void setEnable() {
        setEnable();
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        RechercherBtn1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        RechercherBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        EmployeTree = new javax.swing.JTree();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        IMG = new javax.swing.JLabel();
        salaire = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        prenom = new javax.swing.JTextField();
        code = new javax.swing.JTextField();
        nom = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        initialiser = new javax.swing.JButton();
        update = new javax.swing.JButton();
        valider1 = new javax.swing.JButton();
        Actualisé = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        RechercherBtn2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TABLE = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        code1 = new javax.swing.JTextField();
        nom1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        qentite = new javax.swing.JTextField();
        prix = new javax.swing.JTextField();
        categorie = new javax.swing.JTextField();
        initialiser1 = new javax.swing.JButton();
        valider2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        Actualisé1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        RechercherBtn3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        RechercherBtn4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jTextField6 = new javax.swing.JTextField();
        RechercherBtn5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jTextField7 = new javax.swing.JTextField();
        RechercherBtn6 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 460, -1));

        RechercherBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Serch.png"))); // NOI18N
        RechercherBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RechercherBtn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RechercherBtn1MouseExited(evt);
            }
        });
        RechercherBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RechercherBtn1initialiserActionPerformed(evt);
            }
        });
        jPanel2.add(RechercherBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 20, 20));

        jLabel2.setText("Rechercher");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, -1, 20));

        jTabbedPane1.addTab("Entreprise", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 460, -1));

        RechercherBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Serch.png"))); // NOI18N
        RechercherBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RechercherBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RechercherBtnMouseExited(evt);
            }
        });
        RechercherBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RechercherBtninitialiserActionPerformed(evt);
            }
        });
        jPanel3.add(RechercherBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 20, 20));

        jLabel1.setText("Rechercher");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, -1, 20));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("King");
        EmployeTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        EmployeTree.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                EmployeTreeMouseDragged(evt);
            }
        });
        EmployeTree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmployeTreeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EmployeTreeMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EmployeTreeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                EmployeTreeMouseReleased(evt);
            }
        });
        EmployeTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                EmployeTreeValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(EmployeTree);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 170, 320));

        jLabel10.setText("Salaire");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, -1, -1));

        jLabel9.setText("Age");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, -1, -1));

        jLabel12.setText("Prenom");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));

        jLabel11.setText("Nom");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));

        jLabel13.setText("Code");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        IMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/emp.png"))); // NOI18N
        jPanel3.add(IMG, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 140, 130));
        jPanel3.add(salaire, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 290, -1));
        jPanel3.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 290, -1));
        jPanel3.add(prenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 290, -1));

        code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codenomActionPerformed(evt);
            }
        });
        jPanel3.add(code, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 290, -1));

        nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomnomActionPerformed(evt);
            }
        });
        jPanel3.add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 290, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/chose.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 20, 20));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/profail.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 18, 18));

        jLabel8.setText("Profail");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, 20));

        initialiser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/initialiser.png"))); // NOI18N
        initialiser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                initialiserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                initialiserMouseExited(evt);
            }
        });
        initialiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initialiserinitialiserActionPerformed(evt);
            }
        });
        jPanel3.add(initialiser, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, 20, 20));

        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/update.png"))); // NOI18N
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateMouseExited(evt);
            }
        });
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel3.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 20, 20));

        valider1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Add.png"))); // NOI18N
        valider1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                valider1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                valider1MouseExited(evt);
            }
        });
        valider1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valider1validerActionPerformed(evt);
            }
        });
        jPanel3.add(valider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, 20, 20));

        Actualisé.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        Actualisé.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ActualiséMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ActualiséMouseExited(evt);
            }
        });
        Actualisé.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualiséinitialiserActionPerformed(evt);
            }
        });
        jPanel3.add(Actualisé, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 20, 20));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save (2).png"))); // NOI18N
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, 18, 18));

        jTabbedPane1.addTab("Employe", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 460, -1));

        RechercherBtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Serch.png"))); // NOI18N
        RechercherBtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RechercherBtn2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RechercherBtn2MouseExited(evt);
            }
        });
        RechercherBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RechercherBtn2initialiserActionPerformed(evt);
            }
        });
        jPanel4.add(RechercherBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 20, 20));

        jLabel3.setText("Rechercher");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, -1, 20));

        TABLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TABLE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TABLEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TABLEMouseEntered(evt);
            }
        });
        jScrollPane2.setViewportView(TABLE);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 303, 251));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Produit.png"))); // NOI18N
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        code1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                code1nomActionPerformed(evt);
            }
        });
        jPanel4.add(code1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 130, -1));

        nom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom1nomActionPerformed(evt);
            }
        });
        jPanel4.add(nom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 130, -1));

        jLabel15.setText("Nom de produit");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, 20));

        jLabel16.setText("Code");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, 20));

        jLabel17.setText("Categorie");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, 20));

        jLabel18.setText("Prix");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, 20));

        jLabel19.setText("Qentité");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, 20));
        jPanel4.add(qentite, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 130, -1));
        jPanel4.add(prix, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 130, -1));
        jPanel4.add(categorie, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 130, -1));

        initialiser1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/initialiser.png"))); // NOI18N
        initialiser1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                initialiser1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                initialiser1MouseExited(evt);
            }
        });
        initialiser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initialiser1initialiserActionPerformed(evt);
            }
        });
        jPanel4.add(initialiser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 20, 20));

        valider2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Add.png"))); // NOI18N
        valider2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                valider2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                valider2MouseExited(evt);
            }
        });
        valider2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valider2validerActionPerformed(evt);
            }
        });
        jPanel4.add(valider2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 20, 20));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/update.png"))); // NOI18N
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton4MouseExited(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 20, 20));

        Actualisé1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        Actualisé1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Actualisé1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Actualisé1MouseExited(evt);
            }
        });
        Actualisé1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Actualisé1initialiserActionPerformed(evt);
            }
        });
        jPanel4.add(Actualisé1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, 20, 20));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save (2).png"))); // NOI18N
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton5MouseExited(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 20, 20));

        jTabbedPane1.addTab("Produit", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 460, -1));

        RechercherBtn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Serch.png"))); // NOI18N
        RechercherBtn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RechercherBtn3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RechercherBtn3MouseExited(evt);
            }
        });
        RechercherBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RechercherBtn3initialiserActionPerformed(evt);
            }
        });
        jPanel5.add(RechercherBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 20, 20));

        jLabel4.setText("Rechercher");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, -1, 20));

        jTabbedPane1.addTab("Stock", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel6.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 460, -1));

        RechercherBtn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Serch.png"))); // NOI18N
        RechercherBtn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RechercherBtn4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RechercherBtn4MouseExited(evt);
            }
        });
        RechercherBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RechercherBtn4initialiserActionPerformed(evt);
            }
        });
        jPanel6.add(RechercherBtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 20, 20));

        jLabel5.setText("Rechercher");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, -1, 20));

        jTabbedPane1.addTab("Client", jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel7.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 460, -1));

        RechercherBtn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Serch.png"))); // NOI18N
        RechercherBtn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RechercherBtn5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RechercherBtn5MouseExited(evt);
            }
        });
        RechercherBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RechercherBtn5initialiserActionPerformed(evt);
            }
        });
        jPanel7.add(RechercherBtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 20, 20));

        jLabel6.setText("Rechercher");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, -1, 20));

        jTabbedPane1.addTab("Commande", jPanel7);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel8.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 460, -1));

        RechercherBtn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Serch.png"))); // NOI18N
        RechercherBtn6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RechercherBtn6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RechercherBtn6MouseExited(evt);
            }
        });
        RechercherBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RechercherBtn6initialiserActionPerformed(evt);
            }
        });
        jPanel8.add(RechercherBtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 20, 20));

        jLabel7.setText("Rechercher");
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, -1, 20));

        jTabbedPane1.addTab("A propos", jPanel8);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RechercherBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RechercherBtnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_RechercherBtnMouseEntered

    private void RechercherBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RechercherBtnMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_RechercherBtnMouseExited

    private void RechercherBtninitialiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RechercherBtninitialiserActionPerformed
        
    }//GEN-LAST:event_RechercherBtninitialiserActionPerformed

    private void RechercherBtn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RechercherBtn1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_RechercherBtn1MouseEntered

    private void RechercherBtn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RechercherBtn1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_RechercherBtn1MouseExited

    private void RechercherBtn1initialiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RechercherBtn1initialiserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RechercherBtn1initialiserActionPerformed

    private void RechercherBtn2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RechercherBtn2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_RechercherBtn2MouseEntered

    private void RechercherBtn2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RechercherBtn2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_RechercherBtn2MouseExited

    private void RechercherBtn2initialiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RechercherBtn2initialiserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RechercherBtn2initialiserActionPerformed

    private void RechercherBtn3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RechercherBtn3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_RechercherBtn3MouseEntered

    private void RechercherBtn3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RechercherBtn3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_RechercherBtn3MouseExited

    private void RechercherBtn3initialiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RechercherBtn3initialiserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RechercherBtn3initialiserActionPerformed

    private void RechercherBtn4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RechercherBtn4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_RechercherBtn4MouseEntered

    private void RechercherBtn4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RechercherBtn4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_RechercherBtn4MouseExited

    private void RechercherBtn4initialiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RechercherBtn4initialiserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RechercherBtn4initialiserActionPerformed

    private void RechercherBtn5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RechercherBtn5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_RechercherBtn5MouseEntered

    private void RechercherBtn5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RechercherBtn5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_RechercherBtn5MouseExited

    private void RechercherBtn5initialiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RechercherBtn5initialiserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RechercherBtn5initialiserActionPerformed

    private void RechercherBtn6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RechercherBtn6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_RechercherBtn6MouseEntered

    private void RechercherBtn6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RechercherBtn6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_RechercherBtn6MouseExited

    private void RechercherBtn6initialiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RechercherBtn6initialiserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RechercherBtn6initialiserActionPerformed

    private void EmployeTreeMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeTreeMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_EmployeTreeMouseDragged

    private void EmployeTreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeTreeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_EmployeTreeMouseClicked

    private void EmployeTreeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeTreeMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_EmployeTreeMouseEntered

    private void EmployeTreeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeTreeMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmployeTreeMousePressed

    private void EmployeTreeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeTreeMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_EmployeTreeMouseReleased

    private void EmployeTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_EmployeTreeValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_EmployeTreeValueChanged

    private void codenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codenomActionPerformed

    private void nomnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomnomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomnomActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //JFrame f = new JFrame("Choiser l'image");
        //f.setSize(570, 425);
        //JPanel p = new JPanel();
        //p.setSize(570, 425);
        //p.setBackground(Color.white);
        //f.add(p);
        JFileChooser img = new JFileChooser();

        //img.setCurrentDirectory(new File(System.getProperty(null)));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images", "jpg", "gif", "png");
        img.addChoosableFileFilter(filter);
        int result = img.showSaveDialog(null);
        if(result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = img.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            IMG.setIcon(new ImageIcon(path));
        }
        else if(result == JFileChooser.CANCEL_OPTION){
            System.out.println("CUNCUL");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultTreeModel model = (DefaultTreeModel) EmployeTree.getModel();
        DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) EmployeTree.getLastSelectedPathComponent();
        //if(selectedNode.isRoot())

        if (selectedNode != null) {
            String str = (String) selectedNode.getUserObject();
            Employe corant = new Employe();
            corant = corant.r_Search(str, empList);
            code.setText(corant.Code);
            nom.setText(corant.Nom);
            prenom.setText(corant.getPrenom());
            age.setText(new Integer(corant.Age).toString());
            salaire.setText(new Double(corant.getSalaire()).toString());

            code.setEditable(false);
            nom.setEditable(false);
            prenom.setEditable(false);
            age.setEditable(false);
            salaire.setEditable(false);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void initialiserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_initialiserMouseEntered
        // TODO add your handling code here:
        desc.setText("Actualiser");
    }//GEN-LAST:event_initialiserMouseEntered

    private void initialiserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_initialiserMouseExited
        // TODO add your handling code here:
        desc.setText("");
    }//GEN-LAST:event_initialiserMouseExited

    private void initialiserinitialiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initialiserinitialiserActionPerformed
        // TODO add your handling code here:
        code.setText("");
        nom.setText("");
        prenom.setText("");
        age.setText("");
        salaire.setText("");
        code.setEditable(true);
        nom.setEditable(true);
        prenom.setEditable(true);
        age.setEditable(true);
        salaire.setEditable(true);
    }//GEN-LAST:event_initialiserinitialiserActionPerformed

    private void updateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseEntered
        // TODO add your handling code here:
        desc.setText("Modefier");
    }//GEN-LAST:event_updateMouseEntered

    private void updateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseExited
        // TODO add your handling code here:
        desc.setText("");
    }//GEN-LAST:event_updateMouseExited

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        code.setEditable(true);
        nom.setEditable(true);
        prenom.setEditable(true);
        age.setEditable(true);
        salaire.setEditable(true);
        ModiferBott = true;
    }//GEN-LAST:event_updateActionPerformed

    private void valider1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_valider1MouseEntered
        // TODO add your handling code here:
        desc.setText("Ajouter");
    }//GEN-LAST:event_valider1MouseEntered

    private void valider1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_valider1MouseExited
        // TODO add your handling code here:
        desc.setText("");
    }//GEN-LAST:event_valider1MouseExited

    private void valider1validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valider1validerActionPerformed
        // TODO add your handling code here:
        addEmployeInTree();

        code.setText("");
        nom.setText("");
        prenom.setText("");
        age.setText("");
        salaire.setText("");
    }//GEN-LAST:event_valider1validerActionPerformed

    private void ActualiséMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActualiséMouseEntered
        // TODO add your handling code here:
        desc.setText("Supprimer");
    }//GEN-LAST:event_ActualiséMouseEntered

    private void ActualiséMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActualiséMouseExited
        // TODO add your handling code here:
        desc.setText("");
    }//GEN-LAST:event_ActualiséMouseExited

    private void ActualiséinitialiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualiséinitialiserActionPerformed
        // TODO add your handling code here:
        DefaultTreeModel model = (DefaultTreeModel) EmployeTree.getModel();
        DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) EmployeTree.getLastSelectedPathComponent();
        if(JOptionPane.showConfirmDialog(null, "Vous voullez vraiment supprimer") == 0) {
            if (selectedNode != null) {
                String str = (String) selectedNode.getUserObject();
                if (Employe.remove_employe(empList, str)) {
                    model.removeNodeFromParent(selectedNode);
                } else {
                    selectedNode.setUserObject("Anonyme");
                }
                Employe.SaveEmploye(empList);
            }}
    }//GEN-LAST:event_ActualiséinitialiserActionPerformed

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
        // TODO add your handling code here:
        desc.setText("Souvgarder");
    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
        // TODO add your handling code here:
        desc.setText("");
    }//GEN-LAST:event_jButton3MouseExited

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (ModiferBott) {
            DefaultTreeModel model = (DefaultTreeModel) EmployeTree.getModel();
            DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) EmployeTree.getLastSelectedPathComponent();
            //if(selectedNode.isRoot())

            if (selectedNode != null) {
                String str = (String) selectedNode.getUserObject();
                Employe corant = new Employe();
                corant = corant.r_Search(str, empList);
                Employe t = new Employe(code.getText(), nom.getText(), prenom.getText(), Integer.parseInt(age.getText()), Double.parseDouble(salaire.getText()));
                corant.setCode(t.Code);
                corant.setNom(t.Nom);
                corant.setPrenom(t.getPrenom());
                corant.setAge(t.Age);
                corant.setSalaire(t.getSalaire());
                selectedNode.setUserObject(corant.Nom);
                ModiferBott = false;
            }
        }
        Employe.SaveEmploye(empList);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void TABLEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABLEMouseClicked
        // TODO add your handling code here:
        int row = TABLE.getSelectedRow();

        String co = (TABLE.getModel().getValueAt(row, 0).toString());
        Produit e = Produit.SearchProduit(listProduit, co);
        code.setText(e.Code);
        nom.setText(e.Nom);
        categorie.setText(e.Categorie);
        prix.setText(new Double(e.Prix).toString());
        qentite.setText(new Integer(e.Qentite).toString());

        code.setEditable(false);
        nom.setEditable(false);
        categorie.setEditable(false);
        prix.setEditable(false);
        qentite.setEditable(false);
    }//GEN-LAST:event_TABLEMouseClicked

    private void TABLEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABLEMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_TABLEMouseEntered

    private void code1nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_code1nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_code1nomActionPerformed

    private void nom1nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom1nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom1nomActionPerformed

    private void initialiser1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_initialiser1MouseEntered
        // TODO add your handling code here:
        desc.setText("Actualiser");
    }//GEN-LAST:event_initialiser1MouseEntered

    private void initialiser1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_initialiser1MouseExited
        // TODO add your handling code here:
        desc.setText("Actualiser");
    }//GEN-LAST:event_initialiser1MouseExited

    private void initialiser1initialiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initialiser1initialiserActionPerformed
        // TODO add your handling code here:
        code.setText("");
        nom.setText("");
        categorie.setText("");
        prix.setText("");
        qentite.setText("");
        code.setEditable(true);
        nom.setEditable(true);
        categorie.setEditable(true);
        prix.setEditable(true);
        qentite.setEditable(true);
    }//GEN-LAST:event_initialiser1initialiserActionPerformed

    private void valider2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_valider2MouseEntered
        // TODO add your handling code here:
        desc.setText("Ajouter");
    }//GEN-LAST:event_valider2MouseEntered

    private void valider2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_valider2MouseExited
        // TODO add your handling code here:
        desc.setText("");
    }//GEN-LAST:event_valider2MouseExited

    private void valider2validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valider2validerActionPerformed
        // TODO add your handling code here:
        Produit emp;

        String a = code.getText();
        String b = nom.getText();
        String c = categorie.getText();
        double d = Double.parseDouble(prix.getText());
        int e = Integer.parseInt(qentite.getText());

        if (ModiferBott) {
            emp = Produit.SearchProduit(listProduit, a);
            emp.Code = a;
            emp.Nom = b;
            emp.Categorie = c;
            emp.Prix = d;
            emp.Qentite = e;
            ModiferBott = false;
        } else {
            emp = new Produit(c, b, a, d, e);
            listProduit.add(emp);
        }

        Remplir(listProduit);
        Produit.SaveProduit(listProduit);
        code.setText("");
        categorie.setText("");
        prix.setText("");
        nom.setText("");
        qentite.setText("");
    }//GEN-LAST:event_valider2validerActionPerformed

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered
        // TODO add your handling code here:
        desc.setText("Modifer");
    }//GEN-LAST:event_jButton4MouseEntered

    private void jButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseExited
        // TODO add your handling code here:
        desc.setText("");
    }//GEN-LAST:event_jButton4MouseExited

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        code.setEditable(true);
        nom.setEditable(true);
        categorie.setEditable(true);
        prix.setEditable(true);
        qentite.setEditable(true);

        ModiferBott = true;
    }//GEN-LAST:event_jButton4ActionPerformed

    private void Actualisé1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Actualisé1MouseEntered
        // TODO add your handling code here:
        desc.setText("Supprimer");
    }//GEN-LAST:event_Actualisé1MouseEntered

    private void Actualisé1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Actualisé1MouseExited
        // TODO add your handling code here:
        desc.setText("");
    }//GEN-LAST:event_Actualisé1MouseExited

    private void Actualisé1initialiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Actualisé1initialiserActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Vous voullez vraiment supprimer") == 0) {

            int row = TABLE.getSelectedRow();
            String co = (TABLE.getModel().getValueAt(row, 0).toString());
            Produit e = Produit.SearchProduit(listProduit, co);
            listProduit.remove(e);
            Remplir(listProduit);
            Produit.SaveProduit(listProduit);
        }
    }//GEN-LAST:event_Actualisé1initialiserActionPerformed

    private void jButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseEntered
        // TODO add your handling code here:
        desc.setText("Souvgarder");
    }//GEN-LAST:event_jButton5MouseEntered

    private void jButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseExited
        // TODO add your handling code here:
        desc.setText("");
    }//GEN-LAST:event_jButton5MouseExited

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int row = TABLE.getSelectedRow();
        String co = (TABLE.getModel().getValueAt(row, 0).toString());
        Produit emp;

        String a = code.getText();
        String b = nom.getText();
        String c = categorie.getText();
        double d = Double.parseDouble(prix.getText());
        int e = Integer.parseInt(qentite.getText());

        if (ModiferBott) {
            emp = Produit.SearchProduit(listProduit, co);
            emp.Code = a;
            emp.Nom = b;
            emp.Categorie = c;
            emp.Prix = d;
            emp.Qentite = e;
            ModiferBott = false;
        }
        Remplir(listProduit);
        code.setText("");
        categorie.setText("");
        prix.setText("");
        nom.setText("");
        qentite.setText("");
        Produit.SaveProduit(listProduit);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualisé;
    private javax.swing.JButton Actualisé1;
    private javax.swing.JTree EmployeTree;
    private javax.swing.JLabel IMG;
    private javax.swing.JButton RechercherBtn;
    private javax.swing.JButton RechercherBtn1;
    private javax.swing.JButton RechercherBtn2;
    private javax.swing.JButton RechercherBtn3;
    private javax.swing.JButton RechercherBtn4;
    private javax.swing.JButton RechercherBtn5;
    private javax.swing.JButton RechercherBtn6;
    private javax.swing.JTable TABLE;
    private javax.swing.JTextField age;
    private javax.swing.JTextField categorie;
    private javax.swing.JTextField code;
    private javax.swing.JTextField code1;
    private javax.swing.JButton initialiser;
    private javax.swing.JButton initialiser1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField nom1;
    private javax.swing.JTextField prenom;
    private javax.swing.JTextField prix;
    private javax.swing.JTextField qentite;
    private javax.swing.JTextField salaire;
    private javax.swing.JButton update;
    private javax.swing.JButton valider1;
    private javax.swing.JButton valider2;
    // End of variables declaration//GEN-END:variables
}
